name: Build and Package

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Build
      run: |
        go build -o govworx-recording-agent.exe

    - name: Install Inno Setup
      run: |
        choco install innosetup

    - name: Create MSI
      run: |
        iscc /Qp myscript.iss

    - name: Upload Artifact
      uses: actions/upload-artifact@v2
      with:
        name: myprogram
        path: |
          myprogram.msi
